---

- name: Install package dependencies
  apt:
    name:
     - software-properties-common
     - ubuntu-cloud-keyring
    state: latest
    update_cache: yes
  when: rabbitmq_use_repo

- name: Set up openstack repository
  apt_repository:
    repo: '{{ rabbitmq_repo_deb }}'
    state: present
  when: rabbitmq_use_repo

- name: Install rabbitmq-server
  apt:
    name: 'rabbitmq-server'
    state: latest
    update_cache: yes
